version: '3'

services:
  virtuoso-server:
    image: openlink/virtuoso-opensource-7
    environment:
      - DBA_PASSWORD=123
    volumes:
      - virtuoso-database:/database
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8890"]
      interval: 10s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./backend
    depends_on:
      virtuoso-server:
        condition: service_healthy
    environment:
      - VIRTUOSO_JDBC_URL=jdbc:virtuoso://virtuoso-server:1111/
      - VIRTUOSO_JDBC_USER=dba
      - VIRTUOSO_JDBC_PASSWORD=123
      - VIRTUOSO_GRAPH=http://zatti.alexandre/OntoReD

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: https://practicesforred.com/backend 
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-conf:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend

volumes:
  virtuoso-database:
    driver: local
    driver_opts:
      type: none
      device: ./data/database
      o: bind
  nginx-conf:
    driver: local
    driver_opts:
      type: none
      device: ./nginx/conf
      o: bind
