version: '3'

services:
  virtuoso-server:
    image: openlink/virtuoso-opensource-7
    ports:
      - "1111:1111"
      - "8890:8890"
    environment:
      - DBA_PASSWORD=123
    volumes:
      - ./data/database:/database
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8890"]
      interval: 10s
      timeout: 10s
      retries: 5

  backend:
    image: zatti/tcc-backend:latest
    ports:
      - "8080:8080"
    depends_on:
      virtuoso-server:
        condition: service_healthy
    environment:
      - VIRTUOSO_JDBC_URL=jdbc:virtuoso://virtuoso-server:1111/
      - VIRTUOSO_JDBC_USER=dba
      - VIRTUOSO_JDBC_PASSWORD=123
      - VIRTUOSO_GRAPH=http://zatti.alexandre/OntoReD

  frontend:
    image: zatti/tcc-frontend:latest
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/letsencrypt:/data/letsencrypt
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./data/letsencrypt:/data/letsencrypt
    command: certonly --webroot --webroot-path=/data/letsencrypt --email zatti.alexandre61@gmail.com --agree-tos --no-eff-email --domains practicesforred.online,www.practicesforred.online
    depends_on:
      - nginx

volumes:
  certs:
  certs-data:
