apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  labels:
    name: backend-deploy
    app: backend-gke-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend-pod
      app: backend-gke-deployment
  template:
    metadata:
      name: backend-pod
      labels:
        name: backend-pod
        app: backend-gke-deployment
    spec:
      containers:
        - name: backend
          image: zatti/tcc-backend
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
              memory: "500Mi"
            limits:
              cpu: "200m"
              memory: "500Mi"
          env:
            - name: VIRTUOSO_JDBC_URL
              value: "jdbc:virtuoso://virtuoso-service:1111/"
            - name: VIRTUOSO_JDBC_USER
              value: "dba"
            - name: VIRTUOSO_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: virtuoso-password
            - name: VIRTUOSO_GRAPH
              value: "http://zatti.alexandre/OntoReD"