apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    name: backend-service
    app: backend-gke-deployment
spec:
  type: LoadBalancer
  selector:
    name: backend-pod
    app: backend-gke-deployment
  ports:
    - name: backend
      port: 80
      targetPort: 8080