# renew_before_expiry = 30 days
version = 2.8.0
archive_dir = /etc/letsencrypt/archive/practicesforred.online
cert = /etc/letsencrypt/live/practicesforred.online/cert.pem
privkey = /etc/letsencrypt/live/practicesforred.online/privkey.pem
chain = /etc/letsencrypt/live/practicesforred.online/chain.pem
fullchain = /etc/letsencrypt/live/practicesforred.online/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 2a02356c0ebe9cf39ed0d5bf050c2298
authenticator = webroot
webroot_path = /data/letsencrypt,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
practicesforred.online = /data/letsencrypt
www.practicesforred.online = /data/letsencrypt
