spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
virtuoso.jdbc.url=${VIRTUOSO_JDBC_URL}
virtuoso.jdbc.user=${VIRTUOSO_JDBC_USER}
virtuoso.jdbc.password=${VIRTUOSO_JDBC_PASSWORD}
virtuoso.graph=${VIRTUOSO_GRAPH}

