name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

env:
  GCP_PROJECT_ID: light-zenith-392618
  GKE_CLUSTER_NAME: tcc-cluster
  GKE_CLUSTER_ZONE: southamerica-east1
  IMAGE: zatti/tcc-backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker Login
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        push: true
        tags: ${{ env.IMAGE }}:${{ github.sha }}

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1.1.1
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
        
    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER_NAME }} --zone ${{ env.GKE_CLUSTER_ZONE }} --project ${{ env.GCP_PROJECT_ID }}

    - name: Use gcloud as kubectl authenticator
      run: |
        kubectl config use-context ${{ env.GKE_CLUSTER_NAME }}
        kubectl config set-credentials ${{ env.GKE_CLUSTER_NAME }} --auth-provider=gcp

    - name: Deploy to Kubernetes
      run: |
        # Update the Kubernetes Deployment to use the new image tag
        kubectl set image deployment/backend-deploy backend=${{ env.IMAGE }}:${{ github.sha }}
        
