name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

env:
  GCP_PROJECT_ID: light-zenith-392618
  GKE_CLUSTER_NAME: tcc-cluster
  GKE_CLUSTER_ZONE: southamerica-east1
  IMAGE: zatti/tcc-backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker Login
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        push: true
        tags: ${{ env.IMAGE }}:${{ github.sha }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1.1.1
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}
        
    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@v1.0.2
      with:
        cluster_name: ${{ env.GKE_CLUSTER_NAME }}
        location: ${{ env.GKE_CLUSTER_ZONE }}
        project_id: ${{ env.GCP_PROJECT_ID }}

    - name: Deploy to Kubernetes
      run: |
        # Update the Kubernetes Deployment to use the new image tag
        kubectl set image deployment/backend-deploy backend=${{ env.IMAGE }}:${{ github.sha }}
        
