name: Update Ontology

on:
  push:
    branches:
      - main
    paths:
      - 'OntoReD.rdf'

jobs:
  update-ontology:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send RDF file to Endpoint
        run: |
          curl -X POST -F "file=@OntoReD.rdf" ${{ secrets.BACKEND_API_URL }}/api/ontology/load
